sudo: required
services:
        - docker

before_install:
        - docker build -t 488562/multi-docker -f ./client/Dockerfile.dev ./client

script:
        - docker run 488562/multi-docker npm test -- --coverage

after_success:
        - docker build -t 488562/multi-client ./client
        - docker build -t 488562/multi-nginx ./nginx
        - docker build -t 488562/multi-server ./server
        - docker build -t 488562/multi-worker ./worker
#Log in to the docker hub 
        - echo "$DOCKER_PWD" | docker login -u "$DOCKER_USERID" --password-stdin
        # Take those images and push to the docker hug
        - docker push 488562/multi-client
        - docker push 488562/multi-nginx
        - docker push 488562/multi-server
        - docker push 488562/multi-worker
 

